# Generated by Django 3.0.2 on 2020-01-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200118_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_data',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.User'),
        ),
    ]
