# Generated by Django 3.0.2 on 2020-01-18 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200118_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.ProfileType'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_data',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.User'),
        ),
    ]
