# Generated by Django 3.0.2 on 2020-01-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200109_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
