# Generated by Django 3.0.2 on 2020-01-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200109_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
