# Generated by Django 3.0.2 on 2020-01-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200109_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='authentication_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='authentication_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Type'),
        ),
    ]
