# Generated by Django 3.0.2 on 2020-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200109_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='profile_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
