# Generated by Django 3.0.2 on 2020-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200115_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
