# Generated by Django 3.0.2 on 2020-01-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20200118_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_data',
        ),
    ]
