# Generated by Django 3.0.2 on 2020-01-18 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200118_0237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProfileType',
        ),
    ]
