# Generated by Django 3.0.2 on 2020-01-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20200118_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='profile_type',
        ),
    ]
